stages:
  - Prepare
  - Build
  - Test
  - Benchmark
  - Deploy

# **************************************************************************** #
#                                 Templates                                    #
# **************************************************************************** #

# Year rules
.run-current-year-template:
  tags:
    - linux
    - docker
  variables:
    AOC_CURRENT_YEAR: 2023
    DOCKER_CURRENT_IMAGE: ${CI_REGISTRY_IMAGE}:aoc-${AOC_YEAR}-${CI_COMMIT_SHA}
    DOCKER_LATEST_IMAGE: ${CI_REGISTRY_IMAGE}:aoc-${AOC_YEAR}-latest
  image: ${DOCKER_CURRENT_IMAGE}
  rules:
    - if: '$AOC_CURRENT_YEAR == $AOC_YEAR'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  timeout: 1h
  before_script:
    - env
    - cd ${AOC_YEAR}
    - pwd
    - ls

# Prepare docker
.prepare-docker-template:
  stage: Prepare
  extends:
    .run-current-year-template
  image: docker:20.10.18-git
  services:
    - docker:20.10.18-dind
  before_script:
    - env
    - pwd
    - ls
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker pull ${DOCKER_CURRENT_IMAGE} || true
    - docker pull ${DOCKER_LATEST_IMAGE} || true
    - docker images
  script:
    - >-
      docker build --cache-from ${DOCKER_LATEST_IMAGE}
      --tag ${DOCKER_CURRENT_IMAGE} --tag ${DOCKER_LATEST_IMAGE} ${AOC_YEAR}
    - docker push ${DOCKER_CURRENT_IMAGE}
    - docker push ${DOCKER_LATEST_IMAGE}

# **************************************************************************** #
#                           Advent of Code 2021-2023                           #
# **************************************************************************** #

include:
  - local: '2021/.gitlab-ci.yml'
  - local: '2022/.gitlab-ci.yml'
  - local: '2023/.gitlab-ci.yml'

# **************************************************************************** #
#                               Pages deployment                               #
# **************************************************************************** #

# Create pages with benchmark results
pages:
  stage: Deploy
  tags:
    - linux
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  needs:
    - job: bench ~ aoc-2021
      optional: true
    - job: bench ~ aoc-2022
      optional: true
    - job: bench ~ aoc-2023
      optional: true
  script:
    - mkdir -p public
    - if [ -d "benchmarks_2021" ]; then
    -   mv benchmarks_2021 public/2021
    - fi
    - if [ -d "benchmarks_2022" ]; then
    -   mv benchmarks_2022 public/2022
    - fi
    - if [ -d "benchmarks_2023" ]; then
    -   mv benchmarks_2023 public/2023
    - fi
  artifacts:
    paths:
      - public
