stages:
  - build
  - test
  - bench

# Disables git clone/fetch
.no-git-template:
  variables:
    GIT_STRATEGY: none

# Git update strategy
.git-template:
  variables:
    GIT_STRATEGY: fetch

# **************************************************************************** #
#                            Advent of Code 2021                               #
# **************************************************************************** #

# 2021 Rust template
.rust-template:
  tags:
    - rust
  only:
    - pushes
    - web
    - schedules
  before_script:
    - export PATH="$PATH:/root/.cargo/bin"
    - env
    - cd 2021
    - rustc --version && cargo --version  # Print version info for debugging

# 2021 Rust build
aoc-2021:build:
  stage: "build"
  extends:
    - .git-template
    - .rust-template
  script:
    - cargo build --workspace --verbose

# 2021 Rust test
aoc-2021:test:
  stage: "test"
  extends:
    - .no-git-template
    - .rust-template
  needs:
    - aoc-2021:build
  script:
    - cargo test --workspace --no-fail-fast --verbose

# 2021 Rust benchmark
aoc-2021:bench:
  stage: "bench"
  extends:
    - .no-git-template
    - .rust-template
  needs:
    - aoc-2021:test
  script:
    - cargo bench --workspace --no-fail-fast --verbose
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - target/criterion
