stages:
  - Builds
  - Tests
  - Benchmarks
  - Cleanup

# Disables git clone/fetch
.no-git-template:
  variables:
    GIT_STRATEGY: none

# Git update strategy
.git-template:
  variables:
    GIT_STRATEGY: fetch

# Year rules
.run-current-year-template:
  variables:
    AOC_CURRENT_YEAR: 2022
  rules:
    - if: '$AOC_CURRENT_YEAR == $AOC_YEAR'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

# Freebsd machine template
.bsd-machine-template:
  variables:
    PIPELINE_BASE_DIR: /home/gitlab-runner/aoc-builds
    PIPELINE_DIR: ${PIPELINE_BASE_DIR}/pipe-$CI_PIPELINE_ID

# **************************************************************************** #
#                            Advent of Code 2021                               #
# **************************************************************************** #

# 2021 Rust template
.2021-template:
  tags:
    - AoC
    - Rust
  timeout: 20m
  extends:
    - .bsd-machine-template
  variables:
    AOC_YEAR: 2021
    BUILD_DIR: ${PIPELINE_BASE_DIR}/pipe-$CI_PIPELINE_ID/${AOC_YEAR}
  before_script:
    - export PATH="$PATH:/root/.cargo/bin:$HOME/.cargo/bin"
    - export CARGO_TARGET_DIR=${BUILD_DIR}
    - env
    - pwd
    - ls
    - pushd ${AOC_YEAR}
    - rustc --version && cargo --version  # Print version info for debugging

# 2021 Rust build (debug + release)
aoc-2021 ~ build:
  stage: Builds
  extends:
    - .git-template
    - .2021-template
    - .run-current-year-template
  script:
    - cargo build --workspace --verbose -j1
    - cargo build --release --workspace --verbose -j1

# 2021 Rust test (debug)
aoc-2021 ~ test:
  stage: Tests
  extends:
    - .no-git-template
    - .2021-template
    - .run-current-year-template
  needs:
    - aoc-2021 ~ build
  script:
    - >-
      cargo test --workspace --no-fail-fast --verbose -j1 --
      -Z unstable-options --report-time
  after_script:
    - export PATH="$PATH:/root/.cargo/bin:$HOME/.cargo/bin"
    - export CARGO_TARGET_DIR=${BUILD_DIR}
    - pushd ${AOC_YEAR}
    - >-
      cargo test --workspace --no-fail-fast --verbose -j1 --
      -Z unstable-options --format json --report-time
      | cargo2junit > JUnitReports.xml
  artifacts:
    reports:
      junit: 2021/JUnitReports.xml
    when: always
    expire_in: 1 week

# 2021 Rust fmt check
aoc-2021 ~ format:
  stage: Tests
  extends:
    - .no-git-template
    - .2021-template
  script:
    - cargo fmt --verbose -- --check
  allow_failure: true

# 2021 Rust benchmark (release)
aoc-2021 ~ bench:
  stage: Benchmarks
  extends:
    - .no-git-template
    - .2021-template
    - .run-current-year-template
  needs:
    - aoc-2021 ~ test
    - aoc-2021 ~ format
  script:
    - git clean -dfx .
    - git clone git@github.com:ACSimon33/Advent_of_Code.git -b gh-pages
    - mkdir $BUILD_DIR/criterion
    - mv Advent_of_Code/2021/* $BUILD_DIR/criterion/
    - >-
      cargo bench --workspace --no-fail-fast --verbose -j1 --
      --warm-up-time 1 --measurement-time 2 --sample-size 10
    - pushd Advent_of_Code/2021
    - mv $BUILD_DIR/criterion/* .
    - git add .
    - git commit -m "Updated 2021 benchmark results for commit '$CI_COMMIT_MESSAGE'"
    - git push

# Clean stage
clean:
  stage: Cleanup
  tags:
    - AoC
  timeout: 10m
  extends:
    - .bsd-machine-template
  dependencies: []
  needs:
    - job: aoc-2021 ~ bench
      optional: true
  when: always
  script:
    - echo $PIPELINE_DIR
  after_script:
    - rm -rf $PIPELINE_DIR
