stages:
  - build
  - test
  - benchmark
  - clean

# Disables git clone/fetch
.no-git-template:
  variables:
    GIT_STRATEGY: none

# Git update strategy
.git-template:
  variables:
    GIT_STRATEGY: fetch

# Freebsd machine template
.bsd-machine-template:
  variables:
    PIPELINE_BASE_DIR: /home/gitlab-runner/aoc-builds
    PIPELINE_DIR: ${PIPELINE_BASE_DIR}/pipe-$CI_PIPELINE_ID

# **************************************************************************** #
#                            Advent of Code 2021                               #
# **************************************************************************** #

# 2021 Rust template
.rust-template:
  tags:
    - rust
  only:
    - pushes
    - web
    - schedules
  timeout: 20m
  extends:
    - .bsd-machine-template
  variables:
    BUILD_DIR: ${PIPELINE_BASE_DIR}/pipe-$CI_PIPELINE_ID/2021
  before_script:
    - export PATH="$PATH:/root/.cargo/bin:$HOME/.cargo/bin"
    - export CARGO_TARGET_DIR=${BUILD_DIR}
    - env
    - cd 2021
    - rustc --version && cargo --version  # Print version info for debugging

# 2021 Rust build (debug + release)
aoc-2021:build:
  stage: "build"
  extends:
    - .git-template
    - .rust-template
  script:
    - cargo build --workspace --verbose -j1
    - cargo build --release --workspace --verbose -j1

# 2021 Rust test (debug)
aoc-2021:test:
  stage: "test"
  extends:
    - .no-git-template
    - .rust-template
  needs:
    - aoc-2021:build
  script:
    - >-
      cargo test --workspace --no-fail-fast --verbose -j1 --
      -Z unstable-options --report-time
  after_script:
    - export PATH="$PATH:/root/.cargo/bin:$HOME/.cargo/bin"
    - export CARGO_TARGET_DIR=${BUILD_DIR}
    - cd 2021
    - >-
      cargo test --workspace --no-fail-fast --verbose -j1 --
      -Z unstable-options --format json --report-time
      
  artifacts:
    reports:
      junit: 2021/JUnitReports.xml
    when: always
    expire_in: 1 week

# 2021 Rust fmt check
aoc-2021:format:
  stage: "test"
  extends:
    - .no-git-template
    - .rust-template
  needs:
    - aoc-2021:build
  script:
    - cargo fmt --verbose -- --check
  allow_failure: true

# 2021 Rust benchmark (release)
aoc-2021:bench:
  stage: "benchmark"
  extends:
    - .no-git-template
    - .rust-template
  needs:
    - aoc-2021:test
    - aoc-2021:format
  script:
    - git clean -dfx .
    - git clone git@github.com:ACSimon33/Advent_of_Code.git -b gh-pages
    - mkdir $BUILD_DIR/criterion
    - mv Advent_of_Code/* $BUILD_DIR/criterion/
    - >-
      cargo bench --workspace --no-fail-fast --verbose -j1 --
      --warm-up-time 1 --measurement-time 4 --sample-size 50
    - cd Advent_of_Code
    - mv $BUILD_DIR/criterion/* .
    - git add .
    - git commit -m "Updated benchmark results."
    - git push

# Clean stage
clean:
  stage: "clean"
  tags:
    - rust
  only:
    - pushes
    - web
    - schedules
  timeout: 10m
  extends:
    - .bsd-machine-template
  dependencies: []
  needs:
    - aoc-2021:bench
  when: always
  script:
    - echo $PIPELINE_DIR
  after_script:
    - rm -rf $PIPELINE_DIR
