# **************************************************************************** #
#                            Advent of Code 2022                               #
# **************************************************************************** #

# 2022 template
.2022-template:
  variables:
    AOC_YEAR: 2022

# Prepare docker for 2022
docker ~ aoc-2022:
  extends:
    - .2022-template
    - .prepare-docker-template

# 2022 TypeScript build
build ~ aoc-2022:
  stage: Build
  extends:
    - .2022-template
    - .run-current-year-template
  needs:
    - docker ~ aoc-2022
  script:
    - npm ci && npm run tsc --workspaces

# 2022 TypeScript test
test ~ aoc-2022:
  stage: Test
  extends:
    - .2022-template
    - .run-current-year-template
  needs:
    - build ~ aoc-2022
  script:
    - >-
      npm ci && npm test --workspaces -- --maxWorkers 1 --ci
      --reporters=default --reporters=jest-junit
  artifacts:
    reports:
      junit: 2022/**/junit.xml
    when: always
    expire_in: 1 week

# 2022 TypeScript fmt check
format ~ aoc-2022:
  stage: Test
  extends:
    - .2022-template
    - .run-current-year-template
  needs:
    - docker ~ aoc-2022
    - job: build ~ aoc-2022
      optional: true
  script:
    - npm ci && npm run check-format --workspaces
  allow_failure: true

# 2022 TypeScript benchmark (release)
bench ~ aoc-2022:
  stage: Benchmark
  extends:
    - .2022-template
    - .run-current-year-template
  needs:
    - test ~ aoc-2022
  script:
    - npm ci && npm run tsc --workspaces && npm run benchmark --workspaces
