# **************************************************************************** #
#                            Advent of Code 2021                               #
# **************************************************************************** #

# 2021 template
.2021-template:
  variables:
    AOC_YEAR: 2021

# Prepare docker for 2021
docker ~ aoc-2021:
  extends:
    - .2021-template
    - .prepare-docker-template

# 2021 Rust build (debug + release)
build ~ aoc-2021:
  stage: Build
  extends:
    - .2021-template
    - .run-current-year-template
  needs:
    - docker ~ aoc-2021
  script:
    - cargo build --workspace -j2
    - cargo build --release --workspace --verbose -j2

# 2021 Rust test (debug)
test ~ aoc-2021:
  stage: Test
  extends:
    - .2021-template
    - .run-current-year-template
  needs:
    - build ~ aoc-2021
  script:
    - >-
      cargo test --workspace --no-fail-fast --verbose -j2 --
      -Z unstable-options --report-time
  after_script:
    - >-
      cargo test --workspace --no-fail-fast --verbose -j2 --
      -Z unstable-options --format json --report-time
      | cargo2junit > JUnitReports.xml
  artifacts:
    reports:
      junit: 2021/JUnitReports.xml
    when: always
    expire_in: 1 week

# 2021 Rust fmt check
format ~ aoc-2021:
  stage: Test
  extends:
    - .2021-template
    - .run-current-year-template
  needs:
    - docker ~ aoc-2021
    - job: build ~ aoc-2021
      optional: true
  script:
    - cargo fmt --verbose -- --check
  allow_failure: true

# 2021 Rust benchmark (release)
bench ~ aoc-2021:
  stage: Benchmark
  extends:
    - .2021-template
    - .run-current-year-template
  needs:
    - test ~ aoc-2021
  script:
    - >-
      cargo bench --workspace --no-fail-fast --verbose -j2 --
      --warm-up-time 1 --measurement-time 2 --sample-size 10
    - cd ${CI_PROJECT_DIR}
    - mkdir -p benchmarks_${AOC_YEAR}
    - mv ${AOC_YEAR}/target/criterion/* benchmarks_${AOC_YEAR}
  artifacts:
    paths:
      - benchmarks_${AOC_YEAR}
