[workspace]

members = [
  "2/dive",
  "3/binary_diagnostic",
  "4/giant_squid",
  "5/hydrothermal_venture",
  "6/lanternfish",
  "7/treachery_of_whales",
  "8/seven_segment_search",
  "9/smoke_basin",
  "10/syntax_scoring",
  "11/dumbo_octopus",
  "12/passage_pathing"
]
