name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git checkout main && git pull --all
    - name: Mirror + trigger CI
      uses: ACSimon33/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/ACSimon33/advent_of_code.git"
      env:
        FOLLOW_TAGS: "true"
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "ACSimon33"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "46297496"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
